#!/bin/bash

sleep 2

# xrandr --listmonitors

# No split

# Monitors: 1
#  0: +*DP-3 5120/929x2160/392+0+0  DP-3

# Split 50/50

# Monitors: 2
#  0: LEFT 2560/0x2160/0+0+0  DP-3
#  1: RIGHT 2560/0x2160/0+2560+0  DP-3

# Split 35/65

# Monitors: 2
#  0: LEFT 1792/0x2160/0+0+0  DP-3
#  1: RIGHT 3328/0x2160/0+1792+0  DP-3


EXPECTED_STATUS="+*DP-3 5120/929x2160/392+0+0  DP-3"
if xrandr --listmonitors | grep -Fq "$EXPECTED_STATUS"; then
    # Remember the same config is in i3 config file
    # xrandr --setmonitor LEFT 2560/0x2160/0+0+0 DP-3 --setmonitor RIGHT 2560/0x2160/0+2560+0 DP-3 --output DP-3 --mode 5120x2160 --primary
    xrandr --setmonitor LEFT 1792/0x2160/0+0+0 DP-3 --setmonitor RIGHT 3328/0x2160/0+1792+0 DP-3 --output DP-3 --mode 5120x2160 --primary
    sleep 1
    xrandr -r 120
else
    xrandr --delmonitor LEFT --delmonitor RIGHT
fi

sleep 2

nitrogen --set-scaled --head=0 "/home/kmateusz/RHT/001-corporate/Wallpapers/Desktop/Dark/1-Wallpaper-Red_Hat-4026x2160_Desktop-Black.png"
nitrogen --set-scaled --head=1 "/home/kmateusz/RHT/001-corporate/Wallpapers/Desktop/Dark/1-Wallpaper-Red_Hat-4026x2160_Desktop-Black.png"
